openapi: 3.0.1
info:
  title: Health Check API
  version: 1.0.0
paths:
  /health:
    get:
      summary: Health check endpoint
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  uptime:
                    type: string
                  dbConnected:
                    type: boolean
                  encryptionStatus:
                    type: string
