name: Trigger auto deployment for bloodtrackerapi

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ feature/blood-thinner-medication-tracker ]
    paths:
    - 'src/BloodThinnerTracker.Api/**'
    - 'src/BloodThinnerTracker.Shared/**'
    - 'src/BloodThinnerTracker.ServiceDefaults/**'
    - '.github/workflows/bloodtrackerapi-AutoDeployTrigger-35ca4c93-c6e4-4e72-9d04-ae57bfcba829.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.BLOODTRACKERAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BLOODTRACKERAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BLOODTRACKERAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          acrBuild: true
          appSourcePath: ${{ github.workspace }}/src/BloodThinnerTracker.Api
          registryUrl: 
          registryUsername: ${{ secrets.BLOODTRACKERAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BLOODTRACKERAPI_REGISTRY_PASSWORD }}
          containerAppName: bloodtrackerapi
          resourceGroup: FreeNorthEurope
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          targetPort: 5234
          ingress: external


